\hypertarget{classPyQt6_1_1lupdate_1_1user_1_1UserException}{}\doxysection{Py\+Qt6.\+lupdate.\+user.\+User\+Exception Class Reference}
\label{classPyQt6_1_1lupdate_1_1user_1_1UserException}\index{PyQt6.lupdate.user.UserException@{PyQt6.lupdate.user.UserException}}


Inheritance diagram for Py\+Qt6.\+lupdate.\+user.\+User\+Exception\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=262pt]{classPyQt6_1_1lupdate_1_1user_1_1UserException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for Py\+Qt6.\+lupdate.\+user.\+User\+Exception\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=262pt]{classPyQt6_1_1lupdate_1_1user_1_1UserException__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb} Encapsulate an exception ultimate caused by the user. \end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/\+Py\+Qt6/lupdate/user.\+py\end{DoxyCompactItemize}
