\hypertarget{classpip_1_1__internal_1_1exceptions_1_1BadCommand}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Bad\+Command Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1BadCommand}\index{pip.\_internal.exceptions.BadCommand@{pip.\_internal.exceptions.BadCommand}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1BadCommand__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1BadCommand__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when virtualenv or a command is not found\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
