\hypertarget{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}{}\doxysection{numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception Class Reference}
\label{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}\index{numpy.testing.\_private.utils.KnownFailureException@{numpy.testing.\_private.utils.KnownFailureException}}


Inheritance diagram for numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=235pt]{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=235pt]{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raise this exception to mark a test as a known failing test.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/numpy/testing/\+\_\+private/utils.\+py\end{DoxyCompactItemize}
